# Basic
title: OmnipotentFunnyChicken
subtitle: 一只整天没事摸鱼のUP
welcome_message: <a href="https://github.com/2696791698/2696791698.github.io" target="_blank">下载源码</a>
description: 围在城里的人想逃出来，城外的人想冲进去   ————《围城》
creator: <a href="https://github.com/2696791698">@Omnipotent Funny Chicken</a>

url: "http://www.funnychicken.blog"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/2696791698?tab=projects'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: Omnipotent Funny Chicken
    github: 2696791698
    twitter: Omnipotent Funny Chicken
    gplus: 107108267983477358170
    mail: h2696791698@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
